import type { SidebarCategoryDefinition, SidebarModuleDefinition, SidebarNavItem } from './types';

export const MODULE_FALLBACK: SidebarModuleDefinition[] = [
  { id: 'control', label: 'Control Hub', order: 1000, icon: 'module-control-hub' },
  { id: 'tasks', label: 'Задачи и проекты', order: 2000, icon: 'module-tasks-projects' },
  { id: 'knowledge', label: 'База знаний', order: 3000, icon: 'module-knowledge' },
  { id: 'team', label: 'Команда', order: 4000, icon: 'module-team' },
  { id: 'admin', label: 'Администрирование', order: 5000, icon: 'module-admin' },
];

export const CATEGORY_FALLBACK: SidebarCategoryDefinition[] = [
  { id: 'overview', module_id: 'control', label: 'Обзор', order: 100 },
  { id: 'inbox', module_id: 'control', label: 'Входящие', order: 110 },
  { id: 'calendar', module_id: 'control', label: 'Календарь', order: 120 },
  { id: 'time', module_id: 'control', label: 'Время', order: 130 },
  { id: 'reminders', module_id: 'control', label: 'Напоминания', order: 140 },
  { id: 'tasks', module_id: 'tasks', label: 'Задачи', order: 300 },
  { id: 'projects', module_id: 'tasks', label: 'Проекты', order: 310 },
  { id: 'areas', module_id: 'tasks', label: 'Области', order: 320 },
  { id: 'resources', module_id: 'tasks', label: 'Ресурсы', order: 330 },
  { id: 'knowledge', module_id: 'knowledge', label: 'База знаний', order: 400 },
  { id: 'people', module_id: 'team', label: 'Команда', order: 500 },
  { id: 'habits', module_id: 'team', label: 'Привычки', order: 520 },
  { id: 'settings', module_id: 'admin', label: 'Настройки', order: 600 },
  { id: 'admin_tools', module_id: 'admin', label: 'Администрирование', order: 610 },
];

export const NAV_FALLBACK_ITEMS: SidebarNavItem[] = [
  {
    key: 'overview',
    label: 'Обзор',
    href: '/',
    hidden: true,
    position: 1,
    status: { kind: 'new' },
    module: 'control',
    section_order: 100,
    category: 'overview',
    icon: 'overview',
  },
  {
    key: 'inbox',
    label: 'Входящие',
    href: '/inbox',
    hidden: true,
    position: 2,
    module: 'control',
    section_order: 110,
    category: 'inbox',
    icon: 'inbox',
  },
  {
    key: 'calendar',
    label: 'Календарь',
    href: '/calendar',
    hidden: true,
    position: 3,
    status: { kind: 'new' },
    module: 'control',
    section_order: 120,
    category: 'calendar',
    icon: 'calendar',
  },
  {
    key: 'time',
    label: 'Время',
    href: '/time',
    hidden: true,
    position: 4,
    status: { kind: 'new' },
    module: 'control',
    section_order: 130,
    category: 'time',
    icon: 'time',
  },
  {
    key: 'reminders',
    label: 'Напоминания',
    href: '/reminders',
    hidden: true,
    position: 5,
    status: { kind: 'new' },
    module: 'control',
    section_order: 140,
    category: 'reminders',
    icon: 'reminders',
  },
  {
    key: 'tasks',
    label: 'Задачи',
    href: '/tasks',
    hidden: true,
    position: 6,
    status: { kind: 'wip' },
    module: 'tasks',
    section_order: 300,
    category: 'tasks',
    icon: 'tasks',
  },
  {
    key: 'projects',
    label: 'Проекты',
    href: '/projects',
    hidden: true,
    position: 7,
    status: { kind: 'new' },
    module: 'tasks',
    section_order: 310,
    category: 'projects',
    icon: 'projects',
  },
  {
    key: 'areas',
    label: 'Области',
    href: '/areas',
    hidden: true,
    position: 8,
    status: { kind: 'new' },
    module: 'tasks',
    section_order: 320,
    category: 'areas',
    icon: 'areas',
  },
  {
    key: 'resources',
    label: 'Ресурсы',
    href: '/resources',
    hidden: true,
    position: 9,
    status: { kind: 'wip' },
    module: 'tasks',
    section_order: 330,
    category: 'resources',
    icon: 'resources',
  },
  {
    key: 'notes',
    label: 'Заметки',
    href: '/notes',
    hidden: true,
    position: 10,
    status: { kind: 'new' },
    module: 'knowledge',
    section_order: 400,
    category: 'knowledge',
    icon: 'notes',
  },
  {
    key: 'products',
    label: 'Продукты',
    href: '/products',
    hidden: true,
    position: 11,
    status: { kind: 'new' },
    module: 'knowledge',
    section_order: 410,
    category: 'knowledge',
    icon: 'products',
  },
  {
    key: 'habits',
    label: 'Привычки',
    href: '/habits',
    hidden: true,
    position: 12,
    status: { kind: 'locked', link: '/tariffs' },
    module: 'team',
    section_order: 500,
    category: 'habits',
    icon: 'habits',
  },
  {
    key: 'team',
    label: 'Команда',
    href: '/users',
    hidden: true,
    position: 13,
    status: { kind: 'new' },
    module: 'team',
    section_order: 510,
    category: 'people',
    icon: 'team',
  },
  {
    key: 'groups',
    label: 'Группы',
    href: '/groups',
    hidden: true,
    position: 14,
    status: { kind: 'new' },
    module: 'team',
    section_order: 520,
    category: 'people',
    icon: 'groups',
  },
  {
    key: 'settings',
    label: 'Настройки',
    href: '/settings',
    hidden: true,
    position: 15,
    status: { kind: 'new' },
    module: 'admin',
    section_order: 600,
    category: 'settings',
    icon: 'settings',
  },
  {
    key: 'admin',
    label: 'ЛК Админа',
    href: '/admin',
    hidden: true,
    position: 16,
    status: { kind: 'new' },
    module: 'admin',
    section_order: 610,
    category: 'admin_tools',
    icon: 'admin',
  },
];
