[tool.ruff]
line-length = 88
target-version = "py311"
preview = true

[tool.ruff.lint]
select = ["E", "F", "B", "I", "ASYNC", "TID"]
ignore = ["E203", "E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true

["tool.mypy.core.*"]
strict = true

["tool.mypy.web.*"]
strict = true
