// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/dist/lib/metadata/types/metadata-interface.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/areas/[slug]/page.tsx
{
  const handler = {} as typeof import("../../app/areas/[slug]/page.js")
  handler satisfies AppPageConfig<"/areas/[slug]">
}

// Validate ../../app/areas/page.tsx
{
  const handler = {} as typeof import("../../app/areas/page.js")
  handler satisfies AppPageConfig<"/areas">
}

// Validate ../../app/habits/page.tsx
{
  const handler = {} as typeof import("../../app/habits/page.js")
  handler satisfies AppPageConfig<"/habits">
}

// Validate ../../app/inbox/page.tsx
{
  const handler = {} as typeof import("../../app/inbox/page.js")
  handler satisfies AppPageConfig<"/inbox">
}

// Validate ../../app/page.tsx
{
  const handler = {} as typeof import("../../app/page.js")
  handler satisfies AppPageConfig<"/">
}

// Validate ../../app/projects/[slug]/page.tsx
{
  const handler = {} as typeof import("../../app/projects/[slug]/page.js")
  handler satisfies AppPageConfig<"/projects/[slug]">
}

// Validate ../../app/projects/page.tsx
{
  const handler = {} as typeof import("../../app/projects/page.js")
  handler satisfies AppPageConfig<"/projects">
}

// Validate ../../app/resources/[slug]/page.tsx
{
  const handler = {} as typeof import("../../app/resources/[slug]/page.js")
  handler satisfies AppPageConfig<"/resources/[slug]">
}

// Validate ../../app/resources/page.tsx
{
  const handler = {} as typeof import("../../app/resources/page.js")
  handler satisfies AppPageConfig<"/resources">
}

// Validate ../../app/tasks/page.tsx
{
  const handler = {} as typeof import("../../app/tasks/page.js")
  handler satisfies AppPageConfig<"/tasks">
}

// Validate ../../app/users/[slug]/page.tsx
{
  const handler = {} as typeof import("../../app/users/[slug]/page.js")
  handler satisfies AppPageConfig<"/users/[slug]">
}

// Validate ../../app/users/page.tsx
{
  const handler = {} as typeof import("../../app/users/page.js")
  handler satisfies AppPageConfig<"/users">
}







// Validate ../../app/layout.tsx
{
  const handler = {} as typeof import("../../app/layout.js")
  handler satisfies LayoutConfig<"/">
}
