---
name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps (ripgrep for tests)
        run: |
          sudo apt-get update
          sudo apt-get install -y ripgrep

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --quiet -r requirements.txt

      - name: Lint (flake8)
        run: flake8
        continue-on-error: true

      - name: Run tests
        env:
          TG_BOT_TOKEN: testtoken
          TG_BOT_USERNAME: testbot
        run: pytest -q
        continue-on-error: true

  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: test
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-main
      cancel-in-progress: true

    outputs:
      health: ${{ steps.export_health.outputs.health }}

    steps:
      - name: Add server host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts

      - name: SSH: pull & restart
        id: restart
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script_stop: true
          script: |
            set -euo pipefail
            sudo -u deploy bash -lc '
              set -euo pipefail
              cd /sd/intdata
              mkdir -p ~/.ssh && ssh-keyscan -H github.com >> ~/.ssh/known_hosts
              if git remote get-url origin | grep -q "^https://"; then
                git remote set-url origin git@github.com:LeoTechRu/intData.git
              fi
              git config --global --add safe.directory /sd/intdata || true
              git fetch --prune origin
              git reset --hard origin/main
            '
            sudo -n systemctl restart intdata-bot || true
            sudo -n systemctl restart intdata-web || true

      - name: SSH: health-check (soft)
        id: health
        uses: appleboy/ssh-action@v1.0.0
        continue-on-error: true
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script_stop: false
          script: |
            set -Eeuo pipefail
            # systemd status
            if ! sudo -n systemctl is-active --quiet intdata-web; then exit 1; fi
            if ! sudo -n systemctl is-active --quiet intdata-bot; then exit 1; fi
            # HTTP probe
            if curl -fsS --max-time 5 http://127.0.0.1:5800/auth >/dev/null; then
              echo "OK"
              exit 0
            else
              echo "FAIL"
              exit 1
            fi

      - name: Export health result
        id: export_health
        if: ${{ always() }}
        run: |
          if [ "${{ steps.health.outcome }}" = "success" ]; then
            echo "health=ok" >> "$GITHUB_OUTPUT"
          else
            echo "health=fail" >> "$GITHUB_OUTPUT"
          fi

      - name: Deploy summary
        if: ${{ always() }}
        run: echo "Deploy done. Health = ${{ steps.export_health.outputs.health }}"

  rollback:
    needs: deploy
    if: ${{ needs.deploy.outputs.health == 'fail' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-main
      cancel-in-progress: true

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Guard: avoid rollback loop
        id: guard
        run: |
          last_msg="$(git log -1 --pretty=%B || true)"
          if echo "$last_msg" | grep -qi '\[auto-rollback\]'; then
            echo "do_rollback=no" >> "$GITHUB_ENV"
          else
            echo "do_rollback=yes" >> "$GITHUB_ENV"
          fi

      - name: Create revert commit
        if: env.do_rollback == 'yes'
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          parents="$(git rev-list --parents -n 1 HEAD)"
          n=$(echo "$parents" | wc -w)
          if [ "$n" -ge 3 ]; then
            git revert --no-edit -m 1 HEAD
          else
            git revert --no-edit HEAD
          fi
          git commit --amend -m "$(git log -1 --pretty=%B)

[auto-rollback]"
          git push origin HEAD:main

      - name: SSH: pull reverted & restart
        if: env.do_rollback == 'yes'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script_stop: true
          script: |
            set -euo pipefail
            sudo -u deploy bash -lc '
              set -euo pipefail
              cd /sd/intdata
              git fetch --prune origin
              git reset --hard origin/main
            '
            sudo -n systemctl restart intdata-bot || true
            sudo -n systemctl restart intdata-web || true

      - name: SSH: health-check after rollback
        if: env.do_rollback == 'yes'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script_stop: true
          script: |
            set -Eeuo pipefail
            sudo -n systemctl is-active --quiet intdata-web
            sudo -n systemctl is-active --quiet intdata-bot
            curl -fsS --max-time 5 http://127.0.0.1:5800/auth >/dev/null
            echo "ROLLBACK_HEALTH_OK"
