name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --quiet -r requirements.txt

      - name: Lint (flake8)
        run: flake8 || true

      - name: Run tests
        env:
          TG_BOT_TOKEN: testtoken
          TG_BOT_USERNAME: testbot
        run: pytest -q

