name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add server host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts

      - name: "SSH: pull & restart"
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script_stop: true
          script: |
            set -euo pipefail
            # обновление репозитория
            sudo -u deploy bash -lc '
              set -euo pipefail
              cd /sd/intdata
              mkdir -p ~/.ssh && ssh-keyscan -H github.com >> ~/.ssh/known_hosts
              if git remote get-url origin | grep -q "^https://"; then
                git remote set-url origin git@github.com:LeoTechRu/intData.git
              fi
              git config --global --add safe.directory /sd/intdata || true
              git stash push -u -m "ci-autostash $(date -Iseconds)" || true
              git fetch --prune origin
              git reset --hard origin/main
            '
            # рестарт сервисов
            sudo -n systemctl restart intdata-bot
            sudo -n systemctl restart intdata-web
            # проверка статуса
            systemctl is-active --quiet intdata-bot
            systemctl is-active --quiet intdata-web
