---
name: Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps (ripgrep)
        run: |
          sudo apt-get update
          sudo apt-get install -y ripgrep

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check DB schema up-to-date
        run: python -m core.db.schema_export check

      - name: Run web & diagnostics tests
        timeout-minutes: 20
        env:
          TG_BOT_TOKEN: "testtoken"
          TG_BOT_USERNAME: "testbot"
        run: |
          set -e
          pytest tests/web tests/test_diagnostics_service.py -q | tee pytest-part1.log

      - name: Run remaining tests
        timeout-minutes: 30
        env:
          TG_BOT_TOKEN: "testtoken"
          TG_BOT_USERNAME: "testbot"
        run: |
          set -e
          pytest -q --ignore=tests/web --ignore=tests/test_diagnostics_service.py --maxfail=1 | tee pytest-part2.log

      - name: Upload pytest logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-logs
          path: |
            pytest-part1.log
            pytest-part2.log
